config/routes.rb
Snedda::Application.routes.draw do

  devise_for :users, :skip => [:sessions, :registrations, :passwords]
  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get 'logout' => 'devise/sessions#destroy'

    get 'register' => 'users/registrations#new', :as => :new_user_registration
    post 'register' => 'users/registrations#create', :as => :user_registration

    get 'user' => 'users/registrations#edit', :as => :edit_user_registration
    put 'register' => 'users/registrations#update'

    get 'reset' => 'devise/passwords#new', :as => :new_user_password
    get 'reset_password' => 'devise/passwords#edit', :as => :edit_user_password
    post 'reset' => 'devise/passwords#create', :as => :user_password
    put 'reset' => 'devise/passwords#update'
  end

  namespace :chapters do
    get "chgroup1/chapters"

    get "chgroup2/chapters"

    get "chgroup4/chapters"

    get "chgroup4/chapters"
    get "chgroup5/chapters"

    get "chgroup6/chapters"

    get "chgroup7/chapters"

    get "chgroup8/chapters"

    get "chgroup9/chapters"

    get "chgroup10/chapters"
    get "chgroup11/chapters"
    get "chgroup12/chapters"
    get "chgroup13/chapters"

    get "map/map"
    get "exercises/index"
  end

  root 'home#index'
  get '/index', to: 'home#index'
  get '/payment', to: 'payments#index', as: :new_payment
  post '/payment', to: 'payments#redirect'
  get '/payments/process', to: 'payments#purchase'
  post 'payments/process', to: 'payments#purchase'
  get '/payments/done', to: 'payments#done'
  get '/payment/:user', to: 'payments#redirect', as: :new_redirect_payment

  get 'skopunheimsins', to: 'chapters/chgroup1#chapters'
  get 'heimsmyndin', to: 'chapters/chgroup2#chapters'
  get 'aesirogasynjur', to: 'chapters/chgroup3#chapters'
  get 'valholl', to: 'chapters/chgroup4#chapters'
  get 'sleipnirogskidbladnir', to: 'chapters/chgroup5#chapters'
  get 'forthorstilutgardaloka', to: 'chapters/chgroup6#chapters'
  get 'daudibaldurs', to: 'chapters/chgroup7#chapters'
  get 'ragnarok', to: 'chapters/chgroup8#chapters'

  get 'thjassiogidunn', to: 'chapters/chgroup9#chapters'
  get 'skaldamjodurinn', to: 'chapters/chgroup10#chapters'
  get 'forthors', to: 'chapters/chgroup11#chapters'
  get 'haddur', to: 'chapters/chgroup12#chapters'
  get 'fafnisarfur', to: 'chapters/chgroup13#chapters'

  get 'kort', to: 'chapters/map#map'
  get 'utgafa', to: 'chapters/utgafa#utgafa'

  get 'verkefni', to: 'chapters/exercises#index'
  scope '/verkefni', as: 'verkefni' do 
    get 'ritgerd(/:id)', to: 'chapters/exercises#essay', as: 'ritgerd'
    get 'ritun', to: 'chapters/exercises#writing', as: 'ritun'
    get 'krossar(/:id)', to: 'chapters/exercises#choice', as: 'krossar'
    post 'krossar/:id', to: 'chapters/exercises#choice_check'
    get 'tengi(/:id)', to: 'chapters/exercises#connect', as: 'tengi'
    post 'tengi/:id', to: 'chapters/exercises#connect_check'
    get 'malnotkun', to: 'chapters/exercises#language', as: 'malnotkun'
    get 'tulkun', to: 'chapters/exercises#interpretation', as: 'tulkun'
    get 'krossgatur', to: 'chapters/exercises#crossword', as: 'krossgatur'
  end

  get 'admin' => 'admin/users#index'
  get 'admin/users' => 'admin/users#index', :as => :admin_users
  get 'admin/users/admin/:id' => 'admin/users#admin_enable', :as => :admin_user_admin
  get 'admin/users/purchase/:id' => 'admin/users#admin_purchase', :as => :admin_user_purchase
  delete 'admin/users/purchase/:id' => 'admin/users#admin_clear_purchase'
  delete 'admin/users/admin/:id' => 'admin/users#admin_disable'
  

  delete 'admin/users/:id' => 'admin/users#delete', :as => :admin_user

  namespace :admin do 
    resources :quizzes do 
      resources :questions do 
        resources :answers
      end
    end
    resources :connect_quizzes do
      resources :connect_connections
    end
  end

  

end

app/controllers/chapters/chapter_controller.rb
class Chapters::ChapterController < AuthenticatedController
	layout 'chapters/layouts/application'
	protect_from_forgery with: :exception
end

app/controllers/chapters/chgroup10_controller.rb
# encoding: utf-8

class Chapters::Chgroup10Controller < Chapters::ChapterController
  def chapters    
    @chapter = "Skáldamjöðurinn"
    @chapters = ""
    @audio = "audio/Skaldamjodur"
    @image = "chapters/38-41.jpg"
    # @no_toolbar = true
  end
end

app/controllers/chapters/chgroup11_controller.rb
# encoding: utf-8

class Chapters::Chgroup11Controller < Chapters::ChapterController
  def chapters    
    @chapter = "För Þórs til Geirröðargarða"
    @chapters = ""
    @audio = "audio/ForThorsTil Geirrodargarda"
    @image = "chapters/38-41.jpg"
    # @no_toolbar = true
  end
end

app/controllers/chapters/chgroup12_controller.rb
# encoding: utf-8

class Chapters::Chgroup12Controller < Chapters::ChapterController
  def chapters    
    @chapter = "Haddur Sifjar"
    @chapters = ""
    @audio = "audio/Haddur"
    @image = "chapters/38-41.jpg"
    # @no_toolbar = true
  end
end

app/controllers/chapters/chgroup13_controller.rb
# encoding: utf-8

class Chapters::Chgroup13Controller < Chapters::ChapterController
  def chapters    
    @chapter = "Fáfnisarfur"
    @chapters = ""
    @audio = "audio/Fafnisarfur"
    @image = "chapters/38-41.jpg"
    # @no_toolbar = true
  end
end

app/controllers/chapters/chgroup1_controller.rb
# encoding: utf-8

class Chapters::Chgroup1Controller < Chapters::ChapterController
  def chapters    
    @chapter = "Sköpun heimsins"
    @chapters = "kaflar 1 - 8"
    @audio = "audio/G1"
    @image = "chapters/1-8.jpg"
  end
end

app/controllers/chapters/chgroup2_controller.rb
class Chapters::Chgroup2Controller < Chapters::ChapterController
  def chapters
    @chapter = "Heimsmyndin"
    @chapters = "kaflar 9 - 19"
    @audio = "audio/G2"
    @image = "chapters/9-19.jpg"
  end
end

app/controllers/chapters/chgroup3_controller.rb
# encoding: utf-8

class Chapters::Chgroup3Controller < Chapters::ChapterController
  def chapters
    @chapter = "Æsir og ásynjur"
    @chapters = "kaflar 20 - 37"

    @audio = "audio/G3"
    @image = "chapters/20-37.jpg"
  end
end

app/controllers/chapters/chgroup4_controller.rb
# encoding: utf-8

class Chapters::Chgroup4Controller < Chapters::ChapterController
  def chapters
    @chapter = "Valhöll"
    @chapters = "kaflar 38 - 41"

    @audio = "audio/G4"
    @image = "chapters/38-41.jpg"
  end
end

app/controllers/chapters/chgroup5_controller.rb
# encoding: utf-8

class Chapters::Chgroup5Controller < Chapters::ChapterController
	def chapters
		@chapter = "Sleipnir og Skíðblaðnir"
		@chapters = "kaflar 42 - 43"

	    @audio = "audio/G5"
	    @image = "chapters/42-43.jpg"
  	end
end

app/controllers/chapters/chgroup6_controller.rb
# encoding: utf-8

class Chapters::Chgroup6Controller < Chapters::ChapterController
  def chapters
    @chapter = "För þórs til Útgarða-Loka"
    @chapters = "kaflar 44 - 48"


    @audio = "audio/G6"
    @image = "chapters/44-48.jpg"
  end
end

app/controllers/chapters/chgroup7_controller.rb
# encoding: utf-8

class Chapters::Chgroup7Controller < Chapters::ChapterController
	def chapters
		@chapter = "Dauði Baldurs"
		@chapters = "kaflar 49 - 50"
	    @audio = "audio/G7"
	    @image = "chapters/49-50.jpg"
	end
end

app/controllers/chapters/chgroup8_controller.rb
# encoding: utf-8

class Chapters::Chgroup8Controller < Chapters::ChapterController
	def chapters
	    @chapter = "Ragnarök"
	    @chapters = "kaflar 51 - 54"
	    @audio = "audio/G8"
	    @image = "chapters/51-54.jpg"
	end
end

app/controllers/chapters/chgroup9_controller.rb
# encoding: utf-8

class Chapters::Chgroup9Controller < Chapters::ChapterController
  def chapters    
    @chapter = "Þjassi og Iðunn"
    @chapters = ""
    @audio = "audio/ThjasiOgIdunn"
    @image = "chapters/38-41.jpg"
    
    # @no_toolbar = true
  end
end

app/controllers/chapters/exercises_controller.rb
class Chapters::ExercisesController < Chapters::ChapterController
	before_action :disable_chapters!
	def connect
		@id = params[:id]
		unless @id.nil?
			@quiz = ConnectQuiz.includes(:connections).where(:alias => @id).first
			if @quiz.nil?
				redirect_to :back
				return
			end
			@right, @left = @quiz.connections.partition do |a|
				a.location?
			end
			@left.shuffle!
			@right.shuffle!
			render "chapters/exercises/connect/quiz"
		end
	end
	def connect_check
		@id = params[:id]
		@quiz = ConnectQuiz.includes(:connections).where(:alias => @id).first
		if @quiz.nil?
			redirect_to :back
			return
		end
		@answers = params[:answers] || {}
		@count = @quiz.connections.count/2
		@correct = 0
		@connections = @quiz.connections.to_a.index_by(&:id)
		@answers.each do |k,v|
			if @connections[k.to_i].connect_id == v.to_i
				@correct += 1
			end
		end
		render "chapters/exercises/connect/quiz_check"
	end
	def essay
		@id = params[:id]
		unless @id.nil?
			render "chapters/exercises/essay/#{@id}"
		end
	end
	def writing
	end

	def language
	end

	def interpretation 
	end

	def crossword
	end

	def choice
		@id = params[:id]
		unless @id.nil?
			# render "chapters/exercises/choice/#{@id}/choice_#{@chapter}"
			@quiz = Quiz.includes(questions: [:answers]).where(:alias => @id).first
			if @quiz.nil?
				redirect_to :back
				return
			end
			render "chapters/exercises/choice/quiz"
		end
	end

	def choice_check
		@id = params[:id]
		@quiz = Quiz.includes(questions: [:answers]).where(:alias => @id).first
		if @quiz.nil?
			redirect_to :back
			return
		end
		@answers = params[:answers] || {}
		@count = @quiz.questions.count
		@correct = 0
		@questions = @quiz.questions.to_a.index_by(&:id)
		@answers.each do |k,v|
			if @questions[k.to_i].answers.to_a.index_by(&:id)[v.to_i].correct
				@correct += 1
			end
		end
		render "chapters/exercises/choice/quiz_check"
	end

	private
		def disable_chapters!
			# @no_toolbar = true
			@simple_toolbar = true
			@no_image = true
			@print = true
		end
end

app/controllers/chapters/map_controller.rb
class Chapters::MapController < Chapters::ChapterController
	def map
		# @no_toolbar = true
		@simple_toolbar = true
		@no_image = true
	end
end

app/controllers/chapters/utgafa_controller.rb
class Chapters::UtgafaController < Chapters::ChapterController
	def utgafa
		# @no_toolbar = true
		@simple_toolbar = true
		@no_image = true
	end
end

app/helpers/chapters/chapter_helper.rb
module Chapters::ChapterHelper
	def current_page(page, action = "chapters")
	  if controller.controller_name.to_s == page and controller.action_name.to_s == action
	    'active'
	  else
	    'not_active'
	  end
	end
	def current_group(group)
		g = controller.controller_name.to_s.gsub(/[^\d]/, '').to_i
		if controller.controller_name.to_s == 'map' then g = 1 end
		if controller.controller_name.to_s == 'exercises' then g = 15 end
		ge = 0
		if group == 1 then ge = 1..8 end
		if group == 2 then ge = 9..14 end
		if group == 3 then ge = 15..16 end
		if ge.include? g 
			'active'
		else
			'not_active'
		end
	end
	@@chapters = nil

	def next_page
		@@chapters ||= [
			skopunheimsins_path,
			heimsmyndin_path,
			aesirogasynjur_path,
			valholl_path,
			sleipnirogskidbladnir_path,
			forthorstilutgardaloka_path,
			daudibaldurs_path,
			ragnarok_path,
			thjassiogidunn_path,
			skaldamjodurinn_path,
			forthors_path,
			haddur_path,
			fafnisarfur_path
		]
		path = request.fullpath == '/' ? skopunheimsins_path : request.fullpath
		index = @@chapters.index path
		if index.nil? or @@chapters[index + 1].nil?
			return ''
		else 
			return @@chapters[index + 1]
		end
	end

	def previous_page
		@@chapters ||= [
			skopunheimsins_path,
			heimsmyndin_path,
			aesirogasynjur_path,
			valholl_path,
			sleipnirogskidbladnir_path,
			forthorstilutgardaloka_path,
			daudibaldurs_path,
			ragnarok_path,
			thjassiogidunn_path,
			skaldamjodurinn_path,
			forthors_path,
			haddur_path,
			fafnisarfur_path
		]
		path = request.fullpath == '/' ? skopunheimsins_path : request.fullpath
		index = @@chapters.index path

		if index.nil? or index == 0 or @@chapters[index - 1].nil?
			return ''
		else 
			return @@chapters[index - 1]
		end
	end
end

app/helpers/chapters/chgroup1_helper.rb
module Chapters::Chgroup1Helper
end

app/helpers/chapters/chgroup2_helper.rb
module Chapters::Chgroup2Helper
end

app/views/chapters/exercises/choice.html.slim
.row.exercise
	.col-xs-12
		h1 Krossaspurningar
		.cross
			.inner
				strong.block Gylfaginning
				ul
					li = link_to "Kaflar 1-7", verkefni_krossar_path("g1-7")
					li = link_to "Kaflar 8-10", verkefni_krossar_path("g8-10")
					li = link_to "Kaflar 11-15", verkefni_krossar_path("g11-15")
					li = link_to "Kaflar 16-20", verkefni_krossar_path("g16-20")
					li = link_to "Kaflar 21-25", verkefni_krossar_path("g21-25")
					li = link_to "Kaflar 26-33", verkefni_krossar_path("g26-33")
					li = link_to "Kafli 34", verkefni_krossar_path("g34")
					li = link_to "Kaflar 35-38", verkefni_krossar_path("g35-38")
					li = link_to "Kaflar 39-43", verkefni_krossar_path("g39-43")
					li = link_to "Kaflar 44-47", verkefni_krossar_path("g44-47")
					li = link_to "Kaflar 48-49", verkefni_krossar_path("g48-49")
					li = link_to "Kafli 50", verkefni_krossar_path("g50")
					li = link_to "Kaflar 51-54", verkefni_krossar_path("g51-54")

				strong.block Skáldskaparmál

				ul
					li = link_to "Fáfnisarfur", verkefni_krossar_path("s1")
					li = link_to "För Þórs til Geirröðargarða", verkefni_krossar_path("s2")
					li = link_to "Haddur Sifjar", verkefni_krossar_path("s3")
					li = link_to "Þjassi og Iðunn", verkefni_krossar_path("s4")
					li = link_to "Skáldamjöðurinn", verkefni_krossar_path("s5")

app/views/chapters/exercises/connect.html.slim
.row.exercise
	.col-xs-12
		h1 Tengispurningar
		.connect
			.inner
				strong.block Gylfaginning
				ul
					li 
						== link_to "Bústaður", verkefni_tengi_path("b")
					li 
						== link_to "Einkennishlutir", verkefni_tengi_path("e")
					li 
						== link_to "Systkini", verkefni_tengi_path("systkini")
					li 
						== link_to "Afkvæmi", verkefni_tengi_path("afkvaemi")
					li 
						== link_to "Hjón", verkefni_tengi_path("hjon")
					li 
						== link_to "Hver drepur hvern?", verkefni_tengi_path("hvh")

app/views/chapters/exercises/crossword.html.slim
.row.exercise
	.col-xs-12
		h1 Krossgátur
		ol.custom
			li 
				= link_to "/crosswords/fafnisarfur.pdf" do
					strong Fáfnisarfur
			li 
				= link_to "/crosswords/thorgeirrodagarda.pdf" do
					strong För Þórs til Geirröðargarða og Haddur Sifjar
			li 
				= link_to "/crosswords/thjassiogidunn.pdf" do
					strong Þjasi og Iðunn og Skáldamjöðurinn

app/views/chapters/exercises/essay.html.slim
.row.exercise
	.col-xs-12
		h1 Ritgerðarefni
		.inner
			strong.block = link_to "Gylfaginning", verkefni_ritgerd_path("gylfaginning")
			strong.block = link_to "Skáldskaparmál", verkefni_ritgerd_path("skaldskaparmal")

app/views/chapters/exercises/index.html.slim
.row.exercise
	.col-xs-12
		h1 Verkefni	
		.cross
			h4 Krossaspurningar
			.inner
				strong.block Gylfaginning
				ul
					li = link_to "Kaflar 1-7", verkefni_krossar_path("g1-7")
					li = link_to "Kaflar 8-10", verkefni_krossar_path("g8-10")
					li = link_to "Kaflar 11-15", verkefni_krossar_path("g11-15")
					li = link_to "Kaflar 16-20", verkefni_krossar_path("g16-20")
					li = link_to "Kaflar 21-25", verkefni_krossar_path("g21-25")
					li = link_to "Kaflar 26-33", verkefni_krossar_path("g26-33")
					li = link_to "Kafli 34", verkefni_krossar_path("g34")
					li = link_to "Kaflar 35-38", verkefni_krossar_path("g35-38")
					li = link_to "Kaflar 39-43", verkefni_krossar_path("g39-43")
					li = link_to "Kaflar 44-47", verkefni_krossar_path("g44-47")
					li = link_to "Kaflar 48-49", verkefni_krossar_path("g48-49")
					li = link_to "Kafli 50", verkefni_krossar_path("g50")
					li = link_to "Kaflar 51-54", verkefni_krossar_path("g51-54")

				strong.block Skáldskaparmál

				ul
					li = link_to "Fáfnisarfur", verkefni_krossar_path("s1")
					li = link_to "För Þórs til Geirröðargarða", verkefni_krossar_path("s2")
					li = link_to "Haddur Sifjar", verkefni_krossar_path("s3")
					li = link_to "Þjassi og Iðunn", verkefni_krossar_path("s4")
					li = link_to "Skáldamjöðurinn", verkefni_krossar_path("s5")
		.connect
			h4 Tengispurningar
			.inner
				strong.block Gylfaginning
				ul
					li 
						== link_to "Bústaður", verkefni_tengi_path("b")
					li 
						== link_to "Einkennishlutir", verkefni_tengi_path("e")
					li 
						== link_to "Systkini", verkefni_tengi_path("systkini")
					li 
						== link_to "Afkvæmi", verkefni_tengi_path("afkvaemi")
					li 
						== link_to "Hjón", verkefni_tengi_path("hjon")
					li 
						== link_to "Hver drepur hvern?", verkefni_tengi_path("hvh")
				strong.block Skáldskaparmál
		.essays
			h4 Ritgerðarefni
			.inner
				strong.block = link_to "Gylfaginning", verkefni_ritgerd_path("gylfaginning")
				strong.block = link_to "Skáldskaparmál", verkefni_ritgerd_path("skaldskaparmal")
		.writing
			h4 Ritunarverkefni
			.inner
				strong.block = link_to "Gylfaginning og Skáldskaparmál", verkefni_ritun_path
		.crosswords
			h4 Krossgátur
			.inner
				strong.block = link_to "Gylfaginning og Skáldskaparmál", verkefni_krossgatur_path
		.intrepretation
			h4 Túlkunarspurningar
            .inner
            	strong.block = link_to "Gylfaginning", verkefni_tulkun_path
        .language
        	h4 Málnotkun
        	.inner
	            strong.block = link_to "Gylfaginning", verkefni_malnotkun_path

app/views/chapters/exercises/interpretation.html.slim
.row.exercise
	.col-xs-12
		h1 Túlkunarspurningar (10 – 15 lína svör)
		ol.custom
			li 
				strong Segið frá frásagnarhætti Gylfaginningar, hvernig er upplýsingunum komið á framfæri?

			li 
				strong Berið sköpunina, eins og sagt er frá henni í Gylfaginningu, saman við sköpunarsögu Biblíunnar.
				p Segið frá tveimur hliðstæðum og tveimur andstæðum.

			li 
				strong Segið frá þremur náttúruskýringum sem koma fram í lýsingu á heimsmyndinni í köflum 9 – 17.

			li 
				strong Segið frá þeim tegundum vera sem greint er frá í fyrstu tuttugu köflum Gylfaginningar.
				p Gott gæti verið að setja upp töflu þar sem fram koma heiti, uppruni, eiginleikar, heimkynni og dæmi.

			li 
				strong Óðinn er kallaður fjölda nafna í goðafræðinni og það gildir um fleiri.
				p Sérstaklega er algengt að tvær útgáfur séu af nafni, eins þegar annar sona Loka er kallaður Áli eða Váli. Fleiri sem þetta á við um eru Þór, Loki og Heimdallur. Greinið frá að minnsta kosti tveimur ástæðum sem gætu verið fyrir þessu.

			li 
				strong Annað slagið er sagt frá ásynjum eins og Frigg og Freyju en kafli 35 er sérstaklega helgaður kven-goðunum. 
				p Hvernig ætli standi á því að svo lítið er sagt frá ásynjum miðað við æsi. Á þetta líka við um aðrar skepnur?

			li 
				strong Loki er einn af ásum þó hann sé af jötnakyni.
				p Hann hefur ekkert sérstakt verndarhlutverk eins og Njörður (sjór) eða Bragi (skáldskapur). Hvert er þá hlutverk Loka í goðafræðinni?

			li 
				strong Hvað eiga börn Loka sameiginlegt og hvernig reynast þau ásum á endanum?

			li 
				strong Hver platar hvern í sögunni um það þegar æsir bundu Fenrisúlf?

			li 
				strong Hvað gerði Freyr af sér í tengslum við það þegar hann eignast Gerði fyrir konu og hvernig hefnist honum?

			li 
				strong Segið frá samningnum sem æsir gerðu við borgarsmiðinn.
				p Færið rök fyrir því hver svíkur samninginn.

			li 
				strong Hvaða eiginleika hefur hesturinn Sleipnir?
				p Segið frá þremur öðrum dýrum sem koma fyrir í Gylfaginningu og hafa yfirnáttúrulega eiginleika (t.d. örn, geit, göltur, hafrar).

			li 
				strong Í sögunni um för Þórs til Útgarða-Loka er keppt í ýmsu.
				p Þór og félagar virðast alltaf fara halloka fyrir liði Útgarða-Loka en reynast hafa staðið sig vel þegar ljóstrað er upp um sjónhverfingarnar. Hver gæti verið boðskapur sögunnar í tengslum við þetta?

			li 
				strong Hver er hvati þess að Þór biður um að róa til fiskjar með jötninum Hymi og hvernig tekst til?

			li 
				strong Hvernig er útliti og hlutverki Baldurs lýst í goðafræðinni?
				p Hvaða þýðingu hefur það í tengslum við söguna af dauða hans?

			li 
				strong Um dauða Baldurs segir að það sé mesta óhæfuverk sem unnið hefur verið meðal goða og manna.
				p Hvað var svona slæmt við það?

			li 
				strong Hvert er hlutverk kvenna í sögunni um dauða Baldurs og hvaða viðhorf gæti það endurspeglað?

			li 
				strong Í sögunni af refsingu Loka koma fram tvær náttúruskýringar.
				p Útskýrið.

			li 
				strong Samkvæmt goðafræðinni gerast ragnarök í framtíðinni.
				p Hvernig vita menn þegar þau nálgast?

			li 
				strong Í ýmsum trúarbrögðum er heimsendir tengdur við syndir mannanna.
				p Hvaða syndum manna eða goða tengjast ragnarök?